[@ww.select labelKey="ebDeploymentTask.deploymentAction" name="deploymentAction" list="deploymentActions" require="true" toggle="true"/]
[@ww.textfield labelKey="ebDeploymentTask.accessKey" name="accessKey" required='true'/]
[@ww.textfield labelKey="ebDeploymentTask.secretKey" name="secretKey" required='true'/]
[@ww.textfield labelKey="ebDeploymentTask.region" name="region" required='true'/]
[@ww.textfield labelKey="ebDeploymentTask.applicationName" name="applicationName" required='true'/]
[@ww.textfield labelKey="ebDeploymentTask.environmentName" name="environmentName" required='true'/]
[@ww.textfield labelKey="ebDeploymentTask.s3Bucket" name="s3Bucket" required='true'/]
[@ww.textfield labelKey="ebDeploymentTask.s3Key" name="s3Key" required='true'/]
[@ww.textfield labelKey="ebDeploymentTask.versionLabel" name="versionLabel" required='true'/]